name: Build Latex Document
on: 
  push:
    paths:
    - 'main.tex'
  workflow_dispatch:
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Add / Commit / Push PDF
        run: |
          ls -lt
          git config --global user.name 'Richard Miller'
          git config --global user.email 'richard@ieee.org'
          git add main.pdf
          git commit -m "Git Hub Action: build latex"
          git push
